[package]
name = "dndtrigger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
once_cell = "1.19.0"
plist = "1.6.1"
service-manager = "0.6.0"
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
